export const token =
  'Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3ZXIwNjA5OUBuYXZlci5jb20iLCJhdXRoIjoiTUVNQkVSIiwiZXhwIjoxNzAwNDk2MjkxLCJpYXQiOjE3MDA0OTI2OTF9.opgRoXwjWhhFOmdS40pjZXNJKF3TPux4YDsxp0vcVE0';
